cursor            #f1be6d
cursor_text_color #432c00

foreground            #ece1d4
background            #120d07
selection_foreground  #3d2e16
selection_background  #dbc3a1
url_color             #dbc3a1

#: black 000000 767676
color0  #18130b
color8  #3a342b
#: red cc0403 f2201f
color1  #835f11
color9  #e7b546
#: green 19cb00 23fd00
color2  #dbc3a1
color10 #f9dfbb
#: yellow cecb00 fffd00
color3  #b5cea4
color11 #d1eabe
#: blue 0d73cc 1a8fff
color4  #604100
color12 #f1be6d
#: magenta cb1ed1 fd28ff
color5  #55442a
color13 #dbc3a1
#: cyan 0dcdcd 14ffff
color6  #384c2c
color14 #b5cea4
#: white dddddd ffffff
color7  #d2c4b4
color15 #ece1d4

mark1_foreground #281900
mark1_background #ffdead
mark2_foreground #261904
mark2_background #f9dfbb
mark3_foreground #0d2005
mark3_background #d1eabe

active_tab_foreground #432c00
active_tab_background #f1be6d
inactive_tab_foreground #ffdead
inactive_tab_background #604100

active_border_color #f1be6d
inactive_border_color #432c00
# bell_border_color #ff5a00
