# project: blacknode dotfiles
# file: kitty-wallust-theme.conf
# description: kitty terminal color scheme template for wallust. wallust reads
#              your wallpaper, generates a 16-color palette and injects values
#              into  variables at runtime. register this file in
#              wallust.toml and include the output from kitty.conf.
# author: zhaleff
# repository: https://github.com/zhaleff/blacknode
# license: mit
# permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files, to deal in the software
# without restriction, including without limitation the rights to use, copy,
# modify, merge, publish, distribute, sublicense, and/or sell copies of the
# software, and to permit persons to whom the software is furnished to do so.

# text
foreground              #F7FBFE
background              #010004
selection_foreground    #010004
selection_background    #BB6E44

# cursor
cursor                  #9FC8D3
cursor_text_color       #010004

# urls
url_color               #E8BC5A

# window borders
active_border_color     #F6B7B5
inactive_border_color   #A4A9AC
bell_border_color       #BB6E44

# titlebar
wayland_titlebar_color  system
macos_titlebar_color    system

# tab bar
active_tab_foreground   #010004
active_tab_background   #F7FBFE
inactive_tab_foreground #F7FBFE
inactive_tab_background #010004
tab_bar_background      #010004

# marks
mark1_foreground        #010004
mark1_background        #E8BC5A
mark2_foreground        #010004
mark2_background        #F6B7B5
mark3_foreground        #010004
mark3_background        #DBF0FC

# normal
color0                  #A4A9AC
color1                  #BB6E44
color2                  #4394A9
color3                  #38A16E
color4                  #E8BC5A
color5                  #F6B7B5
color6                  #DBF0FC
color7                  #EAF1F5

# bright
color8                  #A4A9AC
color9                  #BB6E44
color10                 #4394A9
color11                 #38A16E
color12                 #E8BC5A
color13                 #F6B7B5
color14                 #DBF0FC
color15                 #EAF1F5
