cursor                #ffb695
cursor_text_color     #542105

foreground            #f1dfd8
background            #140c09
selection_foreground  #442a1f
selection_background  #e6bead
url_color             #e6bead

color0  #1a120e
color8  #3d332e
color1  #9c3514
color9  #eb815e
color2  #e6bead
color10 #ffdbcc
color3  #d1c88f
color11 #eee4a9
color4  #713619
color12 #ffb695
color5  #5d4034
color13 #e6bead
color6  #4e471b
color14 #d1c88f
color7  #d8c2ba
color15 #f1dfd8

mark1_foreground #351000
mark1_background #ffdbcc
mark2_foreground #2c160c
mark2_background #ffdbcc
mark3_foreground #201c00
mark3_background #eee4a9

active_tab_foreground   #542105
active_tab_background   #ffb695
inactive_tab_foreground #ffdbcc
inactive_tab_background #713619

active_border_color   #ffb695
inactive_border_color #542105
