cursor            #94cdf7
cursor_text_color #00344d

foreground            #dfe3e8
background            #0a0f12
selection_foreground  #21323f
selection_background  #b7c9d9
url_color             #b7c9d9

#: black 000000 767676
color0  #101417
color8  #313539
#: red cc0403 f2201f
color1  #6c362c
color9  #c37b6e
#: green 19cb00 23fd00
color2  #b7c9d9
color10 #d3e5f5
#: yellow cecb00 fffd00
color3  #cec0e8
color11 #eaddff
#: blue 0d73cc 1a8fff
color4  #004c6e
color12 #94cdf7
#: magenta cb1ed1 fd28ff
color5  #384956
color13 #b7c9d9
#: cyan 0dcdcd 14ffff
color6  #4c4163
color14 #cec0e8
#: white dddddd ffffff
color7  #c1c7ce
color15 #dfe3e8

mark1_foreground #001e2f
mark1_background #c9e6ff
mark2_foreground #0c1d29
mark2_background #d3e5f5
mark3_foreground #1f1635
mark3_background #eaddff

active_tab_foreground #00344d
active_tab_background #94cdf7
inactive_tab_foreground #c9e6ff
inactive_tab_background #004c6e

active_border_color #94cdf7
inactive_border_color #00344d
# bell_border_color #ff5a00
