$background = {{background | replace("#", "")}}
$foreground = {{foreground | replace("#", "")}}
$color0 = {{color0 | replace("#", "")}}
$color1 = {{color1 | replace("#", "")}}
$color2 = {{color2 | replace("#", "")}}
$color3 = {{color3 | replace("#", "")}}
$color4 = {{color4 | replace("#", "")}}
$color5 = {{color5 | replace("#", "")}}
$color6 = {{color6 | replace("#", "")}}
$color7 = {{color7 | replace("#", "")}}
