# This is configuration for hyprland, styles of hyprland lockscreen. 
# 5 configs for hyprlock. 
# Copyright (c) 2025 Zhaleff && HollowSec. All Rights Reserved.
# Licence: MIT
# Project: BlackNode
# This is directory for hyprlock
# Repository: https://github.com/zhaleff/BlackNode 
# ----------------------------------------------------------------------

source = $HOME/.config/hypr/hyprlock/style_1.conf 
