source = ~/.config/hypr/ui//mocha.conf

general {
  grace = 3
  background_blur = false
  no_fade_in = false;
  disable_loanding_bar = false
  hide_cursor = true
  ignore_empty_password = false
  immediate_redering = true
}

# Background :D

background {
  monitor =
  path = ~/.local/share/wallpapers/street.png
}

# password

# password
input-field {
    monitor =
    size = 250, 60
    outline_thickness = 2
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    rounding = 50
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(100, 114, 125, 0.6)
    font_color = rgb(200, 200, 200)
    fade_on_empty = false
    font_family = SF Pro Display Bold
    placeholder_text = <i><span foreground="##ffffff99">Hi, $USER</span></i>
    hide_input = false
    position = 0, -150
    halign = center
    valign = center
}

# DATE TIME HOUR
label {
  monitor =
  text = cmd[update:1000] echo "<b><big> $(date +"%H") </big></b>"
  color = $mauve
  position = 0, 100
  font_size = 125
  font_family = JetBrainsMono Nerd Font
  halign = center
  valign = center
}

# DATE TIME MINUTE
label {
  text = cmd[update:1000] echo "<b><big> $(date +"%M") </big></b>"
  color = $text
  monitor  =
  font_family = JetBrainsMono Nerd Font
  font_size = 125
  position =  0, 240
  halign = center
  valign = bottom
}

label {
    monitor =
    text = cmd[update:5000] brightnessctl -m | cut -d, -f4 | tr -d '%' | awk '{printf "󰃞 %s%%", $1}'
    color = $green
    font_size = 16
    font_family = JetBrainsMono Nerd Font
    position = 0, 20
    halign = right
    valign = bottom
}
label {
    monitor =
    text = cmd[update:3000] wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{if($3=="[MUTED]") print "󰝟 OFF"; else printf "󰕾 %.0f%%", $2*100}'
    color = $teal
    font_size = 15
    font_family = JetBrainsMono Nerd Font
    position = 0, 50
    halign = right
    valign = bottom
}
#uptime

label {
  monitor =
  font_family = JetBrainsMono Nerd Font
  text = cmd[update:1000] echo "$(echo -e "Uptime" | uptime -p | sed -e 's/up //g')"
  color = $text
  font_size = 12
  position = 0, 50
  halign = center
  valign = bottom
}

label {
  monitor =
  text = cmd[update:10000] echo "$(~/.config/hypr/hyprlock/Scripts/music.sh"
  color = $text
  font_family = JetBrainsMono Nerd Font
  font_size = 12
  position = -260, 80
  halign = right
  valign = bottom
}
