source = ~/.config/hypr/ui/mocha.conf

general {
  grace = 3
  background_blur = false
  no_fade_in = false;
  disable_loanding_bar = false 
  hide_cursor = true
  ignore_empty_password = false
  immediate_redering = true 
}

# Background :D 

background {
  monitor = 
  path = ~/.local/share/wallpapers/street.png
}

# password 
input-field {
    monitor =
    background = rgba(30, 30, 30, 0.70)
    color = rgba(180, 190, 254)
    size = 200, 60
    outline_thickness = 2
    dot_size = 0.30
    rounding = 10
    dots_spacing = true
    dots_center = true
    outer_color = 
    nner_color = rgba(203, 166, 247)
    font_color = rgba(205, 214, 244)
    fade_on_empty = true
    placeholder_text = <i>Hello, $USER</i> # Text rendered in th>
    hide_input = false
    position = 140, 0
    halign = center
    valign = center
}
# DATE TIME HOUR 
label {
  monitor = 
  text = cmd[update:1000] echo "<b><big> $(date +"%H") </big></b>" 
  color = $mauve
  position = 116, 0
  font_size = 110
  font_family = JetBrainsMono Nerd Font
  halign = center
  valign = center
}

# DATE TIME MINUTE
label {
  text = cmd[update:1000] echo "<b><big> $(date +"%M") </big></b>"
  color = $text
  monitor  = 
  font_family = JetBrainsMono Nerd Font
  font_size = 120
  position =  100, 0
  halign = center 
  valign = bottom 
}

# Power
label {
    monitor =
    text = 󰐥  󰜉  󰤄
    color = rgba(255, 255, 255, 0.6)
    font_size = 50
    position = 160, 100
    halign = left
    valign = bottom
}

#uptime

label {
  monitor = 
  font_family = JetBrainsMono Nerd Font
  text = cmd[update:1000] echo "$(echo -e "Uptime" | uptime -p | sed -e 's/up //g')"
  color = $text
  font_size = 12
  position = -410, 130
  halign = right
  valign = bottom
}

label {
  monitor = 
  text = cmd[update:10000] echo "$(~/.config/hypr/scripts/songdetail.sh)"
  color = $text
  font_family = JetBrainsMono Nerd Font
  font_size = 12 
  position = -260, 80 
  halign = center
  valign = bottom
}


label {
  monitor = 
  text = cmd[update:10000000000] echo "$(~/.config/hypr/scripts/ipaddr.sh)"
  color = $text
  font_family = JetBrainsMono Nerd Font
  font_size = 12 
  position = -260, 110 
  halign = center
  valign = bottom
}
