#!/usr/bin/env bash
if pgrep -x wf-recorder >/dev/null 2>&1; then
    echo '{"text":"󰀽","tooltip":"Recording","class":"recording"}'
else
    echo '{"text":"󰀽","tooltip":"Not recording","class":"idle"}'
fi
