# ================================
#  HYPRLOCK — Matugen + Playfair + Grotesk
# ================================

# BACKGROUND
background {
    monitor =
    path = ~/.config/hypr/lockscreen.png
    color = rgba(${colors.primary_container.rgb})
    blur_passes = 3
    blur_size = 8
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# GENERAL
general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = false
}

# PROFILE PHOTO
image {
    monitor =
    path = ~/.config/hyprlock/profile.png
    border_size = 2
    border_color = rgba(${colors.primary.rgb})
    size = 100
    rounding = -1
    rotate = 0
    reload_time = -1
    position = 0, 200
    halign = center
    valign = center
}

# NAME
label {
    monitor =
    text = $USER
    color = rgba(${colors.on_surface.rgb})
    outline_thickness = 0
    font_size = 20
    font_family = "Familjen Grotesk"
    position = 0, 110
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%H:%M')"
    color = rgba(${colors.on_surface.rgb})
    font_size = 96
    font_family = "Playfair Display"
    position = 0, 0
    halign = center
    valign = center
}

# DAY - MONTH - DATE
label {
    monitor =
    text = cmd[update:18000000] echo "$(date +'%A, %d %B %Y')"
    color = rgba(${colors.on_surface_variant.rgb})
    font_size = 18
    font_family = "Familjen Grotesk"
    position = 0, -60
    halign = center
    valign = center
}

# USER-BOX
shape {
    monitor =
    size = 320, 55
    color = rgba(${colors.surface.rgb})
    rounding = 24
    border_size = 1
    border_color = rgba(${colors.outline.rgb})
    rotate = 0
    xray = false
    position = 0, -160
    halign = center
    valign = center
}

# USER LABEL (dentro del box)
label {
    monitor =
    text = $USER
    color = rgba(${colors.on_surface.rgb})
    outline_thickness = 0
    font_size = 16
    font_family = "Familjen Grotesk"
    position = 0, -160
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 320, 55
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.5
    dots_center = true
    outer_color = rgba(${colors.primary.rgb})
    inner_color = rgba(${colors.surface.rgb})
    font_color = rgba(${colors.on_surface.rgb})
    fade_on_empty = true
    fade_timeout = 1000
    dots_rounding = -1
    cap_color = rgba(${colors.primary.rgb})
    check_color = rgba(${colors.primary.rgb})
    fail_color = rgba(${colors.error.rgb})
    fail_text = <i>$FAIL</i>
    fail_transition = 300
    transition_time = 200
    hide_input = false
    rounding = 24
    font_family = "Familjen Grotesk"
    placeholder_text = <i><span foreground="##ffffff99"> Enter Pass</span></i>
    position = 0, -240
    halign = center
    valign = center
}
