-- Generated by matugen for Hyprland v0.55 (Lua config)
-- Project: BlackNode
-- File: themes/colors.lua

background = "{{colors.surface.default.hex_stripped}}"
foreground = "{{colors.on_surface.default.hex_stripped}}"

color0 = "{{colors.surface.default.hex_stripped}}"
color1 = "{{colors.primary.default.hex_stripped}}"
color2 = "{{colors.secondary.default.hex_stripped}}"
color3 = "{{colors.tertiary.default.hex_stripped}}"
color4 = "{{colors.primary_container.default.hex_stripped}}"
color5 = "{{colors.secondary_container.default.hex_stripped}}"
color6 = "{{colors.tertiary_container.default.hex_stripped}}"
color7 = "{{colors.on_surface.default.hex_stripped}}"

color8 = "{{colors.surface_variant.default.hex_stripped}}"
color9 = "{{colors.primary.default.hex_stripped}}"
color10 = "{{colors.secondary.default.hex_stripped}}"
color11 = "{{colors.tertiary.default.hex_stripped}}"
color12 = "{{colors.primary_container.default.hex_stripped}}"
color13 = "{{colors.secondary_container.default.hex_stripped}}"
color14 = "{{colors.tertiary_container.default.hex_stripped}}"
color15 = "{{colors.inverse_on_surface.default.hex_stripped}}"
