-- Generated by Matugen
-- BlackNode
vim.o.termguicolors = true
vim.cmd("hi clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end

local hl = vim.api.nvim_set_hl

local colors = {
  bg = "{{colors.background.default.hex}}",
  fg = "{{colors.on_surface.default.hex}}",

  primary = "{{colors.primary.default.hex}}",
  on_primary = "{{colors.on_primary.default.hex}}",
  primary_container = "{{colors.primary_container.default.hex}}",
  on_primary_container = "{{colors.on_primary_container.default.hex}}",

  secondary = "{{colors.secondary.default.hex}}",
  on_secondary = "{{colors.on_secondary.default.hex}}",
  secondary_container = "{{colors.secondary_container.default.hex}}",
  on_secondary_container = "{{colors.on_secondary_container.default.hex}}",

  tertiary = "{{colors.tertiary.default.hex}}",
  on_tertiary = "{{colors.on_tertiary.default.hex}}",
  tertiary_container = "{{colors.tertiary_container.default.hex}}",
  on_tertiary_container = "{{colors.on_tertiary_container.default.hex}}",

  surface = "{{colors.surface_container.default.hex}}",
  surface_low = "{{colors.surface_container_low.default.hex}}",
  surface_high = "{{colors.surface_container_high.default.hex}}",
  surface_bright = "{{colors.surface_bright.default.hex}}",
  surface_dim = "{{colors.surface_dim.default.hex}}",
  on_surface = "{{colors.on_surface.default.hex}}",
  on_surface_variant = "{{colors.on_surface_variant.default.hex}}",

  outline = "{{colors.outline.default.hex}}",
  outline_variant = "{{colors.outline_variant.default.hex}}",

  error = "{{colors.error.default.hex}}",
  on_error = "{{colors.on_error.default.hex}}",
  error_container = "{{colors.error_container.default.hex}}",

  shadow = "{{colors.shadow.default.hex}}",
  inverse_surface = "{{colors.inverse_surface.default.hex}}",
  inverse_on_surface = "{{colors.inverse_on_surface.default.hex}}",
}

hl(0, "Normal", { fg = colors.fg, bg = colors.bg })
hl(0, "NormalNC", { fg = colors.fg, bg = colors.bg })
hl(0, "NormalFloat", { fg = colors.fg, bg = colors.surface })
hl(0, "FloatBorder", { fg = colors.outline, bg = colors.surface })
hl(0, "FloatTitle", { fg = colors.primary, bg = colors.surface, bold = true })

hl(0, "Cursor", { fg = colors.bg, bg = colors.fg })
hl(0, "CursorLine", { bg = colors.surface_low })
hl(0, "CursorLineNr", { fg = colors.primary, bold = true })
hl(0, "CursorColumn", { bg = colors.surface_low })
hl(0, "ColorColumn", { bg = colors.surface_low })

hl(0, "LineNr", { fg = colors.outline })
hl(0, "SignColumn", { bg = colors.bg })
hl(0, "EndOfBuffer", { fg = colors.bg })
hl(0, "Whitespace", { fg = colors.outline_variant })
hl(0, "NonText", { fg = colors.outline_variant })
hl(0, "SpecialKey", { fg = colors.outline_variant })
hl(0, "Conceal", { fg = colors.outline })

hl(0, "Visual", { fg = colors.on_primary_container, bg = colors.primary_container })
hl(0, "VisualNOS", { fg = colors.on_primary_container, bg = colors.primary_container })

hl(0, "Search", { fg = colors.on_tertiary_container, bg = colors.tertiary_container })
hl(0, "IncSearch", { fg = colors.on_tertiary, bg = colors.tertiary })
hl(0, "CurSearch", { fg = colors.on_tertiary, bg = colors.tertiary })

hl(0, "Pmenu", { fg = colors.fg, bg = colors.surface })
hl(0, "PmenuSel", { fg = colors.on_primary_container, bg = colors.primary_container })
hl(0, "PmenuSbar", { bg = colors.surface_low })
hl(0, "PmenuThumb", { bg = colors.outline })
hl(0, "PmenuKind", { fg = colors.secondary, bg = colors.surface })
hl(0, "PmenuKindSel", { fg = colors.on_primary_container, bg = colors.primary_container })
hl(0, "PmenuExtra", { fg = colors.outline, bg = colors.surface })
hl(0, "PmenuExtraSel", { fg = colors.on_primary_container, bg = colors.primary_container })

hl(0, "StatusLine", { fg = colors.fg, bg = colors.surface })
hl(0, "StatusLineNC", { fg = colors.outline, bg = colors.bg })
hl(0, "WinSeparator", { fg = colors.outline_variant })
hl(0, "VertSplit", { fg = colors.outline_variant })

hl(0, "TabLine", { fg = colors.outline, bg = colors.surface_low })
hl(0, "TabLineSel", { fg = colors.on_primary_container, bg = colors.primary_container })
hl(0, "TabLineFill", { bg = colors.bg })

hl(0, "Title", { fg = colors.primary, bold = true })
hl(0, "Directory", { fg = colors.primary })
hl(0, "MoreMsg", { fg = colors.primary })
hl(0, "Question", { fg = colors.primary })
hl(0, "ModeMsg", { fg = colors.fg, bold = true })
hl(0, "MsgArea", { fg = colors.fg })
hl(0, "MsgSeparator", { fg = colors.outline })
hl(0, "WarningMsg", { fg = colors.tertiary })
hl(0, "ErrorMsg", { fg = colors.error })

hl(0, "MatchParen", { fg = colors.tertiary, bold = true, underline = true })
hl(0, "WildMenu", { fg = colors.on_primary_container, bg = colors.primary_container })

hl(0, "DiffAdd", { fg = colors.on_tertiary_container, bg = colors.tertiary_container })
hl(0, "DiffChange", { fg = colors.on_secondary_container, bg = colors.secondary_container })
hl(0, "DiffDelete", { fg = colors.on_error, bg = colors.error_container })
hl(0, "DiffText", { fg = colors.on_primary_container, bg = colors.primary_container, bold = true })

hl(0, "Folded", { fg = colors.outline, bg = colors.surface_low })
hl(0, "FoldColumn", { fg = colors.outline })

hl(0, "SpellBad", { sp = colors.error, undercurl = true })
hl(0, "SpellCap", { sp = colors.secondary, undercurl = true })
hl(0, "SpellLocal", { sp = colors.tertiary, undercurl = true })
hl(0, "SpellRare", { sp = colors.primary, undercurl = true })


hl(0, "Comment", { fg = colors.outline, italic = true })

hl(0, "Constant", { fg = colors.secondary })
hl(0, "String", { fg = colors.tertiary })
hl(0, "Character", { fg = colors.tertiary })
hl(0, "Number", { fg = colors.secondary })
hl(0, "Boolean", { fg = colors.secondary })
hl(0, "Float", { fg = colors.secondary })

hl(0, "Identifier", { fg = colors.fg })
hl(0, "Function", { fg = colors.primary })

hl(0, "Statement", { fg = colors.secondary })
hl(0, "Conditional", { fg = colors.secondary })
hl(0, "Repeat", { fg = colors.secondary })
hl(0, "Label", { fg = colors.secondary })
hl(0, "Operator", { fg = colors.on_surface_variant })
hl(0, "Keyword", { fg = colors.secondary })
hl(0, "Exception", { fg = colors.secondary })

hl(0, "PreProc", { fg = colors.primary })
hl(0, "Include", { fg = colors.primary })
hl(0, "Define", { fg = colors.primary })
hl(0, "Macro", { fg = colors.primary })
hl(0, "PreCondit", { fg = colors.primary })

hl(0, "Type", { fg = colors.primary_container })
hl(0, "StorageClass", { fg = colors.secondary })
hl(0, "Structure", { fg = colors.primary_container })
hl(0, "Typedef", { fg = colors.primary_container })

hl(0, "Special", { fg = colors.tertiary })
hl(0, "SpecialChar", { fg = colors.tertiary })
hl(0, "Tag", { fg = colors.primary })
hl(0, "Delimiter", { fg = colors.on_surface_variant })
hl(0, "SpecialComment", { fg = colors.outline, italic = true })
hl(0, "Debug", { fg = colors.error })

hl(0, "Underlined", { underline = true })
hl(0, "Ignore", { fg = colors.outline })
hl(0, "Error", { fg = colors.on_error, bg = colors.error_container })
hl(0, "Todo", { fg = colors.on_tertiary_container, bg = colors.tertiary_container, bold = true })

local ts = {
  ["@variable"] = { fg = colors.fg },
  ["@variable.builtin"] = { fg = colors.secondary, italic = true },
  ["@variable.parameter"] = { fg = colors.on_surface_variant },
  ["@variable.parameter.builtin"] = { fg = colors.secondary },
  ["@variable.member"] = { fg = colors.primary },

  ["@constant"] = { fg = colors.secondary },
  ["@constant.builtin"] = { fg = colors.secondary, bold = true },
  ["@constant.macro"] = { fg = colors.secondary },

  ["@module"] = { fg = colors.primary },
  ["@module.builtin"] = { fg = colors.primary },
  ["@namespace"] = { fg = colors.primary },
  ["@label"] = { fg = colors.secondary },

  ["@string"] = { fg = colors.tertiary },
  ["@string.documentation"] = { fg = colors.outline, italic = true },
  ["@string.regexp"] = { fg = colors.tertiary_container },
  ["@string.escape"] = { fg = colors.tertiary_container, bold = true },
  ["@string.special"] = { fg = colors.tertiary_container },
  ["@string.special.symbol"] = { fg = colors.secondary },
  ["@string.special.url"] = { fg = colors.primary, underline = true },
  ["@character"] = { fg = colors.tertiary },
  ["@character.special"] = { fg = colors.tertiary_container },

  ["@number"] = { fg = colors.secondary },
  ["@number.float"] = { fg = colors.secondary },
  ["@boolean"] = { fg = colors.secondary, bold = true },

  ["@function"] = { fg = colors.primary },
  ["@function.builtin"] = { fg = colors.primary, italic = true },
  ["@function.call"] = { fg = colors.primary },
  ["@function.macro"] = { fg = colors.primary },
  ["@function.method"] = { fg = colors.primary },
  ["@function.method.call"] = { fg = colors.primary },
  ["@method"] = { fg = colors.primary },
  ["@method.call"] = { fg = colors.primary },
  ["@constructor"] = { fg = colors.primary_container, bold = true },
  ["@parameter"] = { fg = colors.on_surface_variant },

  ["@operator"] = { fg = colors.on_surface_variant },

  ["@keyword"] = { fg = colors.secondary },
  ["@keyword.function"] = { fg = colors.secondary },
  ["@keyword.operator"] = { fg = colors.secondary },
  ["@keyword.return"] = { fg = colors.secondary, bold = true },
  ["@keyword.import"] = { fg = colors.primary },
  ["@keyword.repeat"] = { fg = colors.secondary },
  ["@keyword.conditional"] = { fg = colors.secondary },
  ["@keyword.exception"] = { fg = colors.secondary },
  ["@keyword.coroutine"] = { fg = colors.secondary },
  ["@keyword.type"] = { fg = colors.secondary },
  ["@keyword.modifier"] = { fg = colors.secondary },
  ["@keyword.directive"] = { fg = colors.primary },

  ["@punctuation.delimiter"] = { fg = colors.on_surface_variant },
  ["@punctuation.bracket"] = { fg = colors.on_surface_variant },
  ["@punctuation.special"] = { fg = colors.tertiary },

  ["@comment"] = { fg = colors.outline, italic = true },
  ["@comment.documentation"] = { fg = colors.outline, italic = true },
  ["@comment.error"] = { fg = colors.error },
  ["@comment.warning"] = { fg = colors.tertiary },
  ["@comment.todo"] = { fg = colors.on_tertiary_container, bg = colors.tertiary_container, bold = true },
  ["@comment.note"] = { fg = colors.on_primary_container, bg = colors.primary_container },

  ["@markup.strong"] = { bold = true },
  ["@markup.italic"] = { italic = true },
  ["@markup.strikethrough"] = { strikethrough = true },
  ["@markup.underline"] = { underline = true },
  ["@markup.heading"] = { fg = colors.primary, bold = true },
  ["@markup.link"] = { fg = colors.primary, underline = true },
  ["@markup.link.url"] = { fg = colors.primary, underline = true },
  ["@markup.link.label"] = { fg = colors.secondary },
  ["@markup.raw"] = { fg = colors.tertiary },
  ["@markup.list"] = { fg = colors.secondary },
  ["@markup.quote"] = { fg = colors.outline, italic = true },

  ["@type"] = { fg = colors.primary_container },
  ["@type.builtin"] = { fg = colors.primary_container, italic = true },
  ["@type.definition"] = { fg = colors.primary_container },
  ["@attribute"] = { fg = colors.secondary },
  ["@property"] = { fg = colors.primary },
  ["@field"] = { fg = colors.primary },

  ["@tag"] = { fg = colors.primary },
  ["@tag.builtin"] = { fg = colors.primary },
  ["@tag.attribute"] = { fg = colors.secondary },
  ["@tag.delimiter"] = { fg = colors.outline },

  ["@diff.plus"] = { fg = colors.tertiary },
  ["@diff.minus"] = { fg = colors.error },
  ["@diff.delta"] = { fg = colors.secondary },
}

for group, opts in pairs(ts) do
  hl(0, group, opts)
end

hl(0, "@lsp.type.class", { fg = colors.primary_container })
hl(0, "@lsp.type.decorator", { fg = colors.secondary })
hl(0, "@lsp.type.enum", { fg = colors.primary_container })
hl(0, "@lsp.type.enumMember", { fg = colors.secondary })
hl(0, "@lsp.type.function", { fg = colors.primary })
hl(0, "@lsp.type.interface", { fg = colors.primary_container })
hl(0, "@lsp.type.macro", { fg = colors.primary })
hl(0, "@lsp.type.method", { fg = colors.primary })
hl(0, "@lsp.type.namespace", { fg = colors.primary })
hl(0, "@lsp.type.parameter", { fg = colors.on_surface_variant })
hl(0, "@lsp.type.property", { fg = colors.primary })
hl(0, "@lsp.type.struct", { fg = colors.primary_container })
hl(0, "@lsp.type.type", { fg = colors.primary_container })
hl(0, "@lsp.type.typeParameter", { fg = colors.primary_container })
hl(0, "@lsp.type.variable", { fg = colors.fg })

hl(0, "DiagnosticError", { fg = colors.error })
hl(0, "DiagnosticWarn", { fg = colors.tertiary })
hl(0, "DiagnosticInfo", { fg = colors.primary })
hl(0, "DiagnosticHint", { fg = colors.secondary })
hl(0, "DiagnosticOk", { fg = colors.tertiary })
hl(0, "DiagnosticUnderlineError", { sp = colors.error, undercurl = true })
hl(0, "DiagnosticUnderlineWarn", { sp = colors.tertiary, undercurl = true })
hl(0, "DiagnosticUnderlineInfo", { sp = colors.primary, undercurl = true })
hl(0, "DiagnosticUnderlineHint", { sp = colors.secondary, undercurl = true })
hl(0, "DiagnosticVirtualTextError", { fg = colors.error, bg = colors.error_container })
hl(0, "DiagnosticVirtualTextWarn", { fg = colors.tertiary, bg = colors.surface_low })
hl(0, "DiagnosticVirtualTextInfo", { fg = colors.primary, bg = colors.surface_low })
hl(0, "DiagnosticVirtualTextHint", { fg = colors.secondary, bg = colors.surface_low })



-- Telescope
hl(0, "TelescopeNormal", { fg = colors.fg, bg = colors.surface })
hl(0, "TelescopeBorder", { fg = colors.primary, bg = colors.surface })
hl(0, "TelescopePromptNormal", { fg = colors.fg, bg = colors.surface_low })
hl(0, "TelescopePromptBorder", { fg = colors.primary, bg = colors.surface_low })
hl(0, "TelescopePromptPrefix", { fg = colors.primary })
hl(0, "TelescopePromptTitle", { fg = colors.on_primary_container, bg = colors.primary_container })
hl(0, "TelescopePreviewTitle", { fg = colors.on_tertiary_container, bg = colors.tertiary_container })
hl(0, "TelescopeResultsTitle", { fg = colors.on_secondary_container, bg = colors.secondary_container })
hl(0, "TelescopeSelection", { fg = colors.on_primary_container, bg = colors.primary_container })
hl(0, "TelescopeSelectionCaret", { fg = colors.primary })
hl(0, "TelescopeMatching", { fg = colors.tertiary, bold = true })

-- NvimTree
hl(0, "NvimTreeNormal", { fg = colors.fg, bg = colors.bg })
hl(0, "NvimTreeWinSeparator", { fg = colors.outline_variant, bg = colors.bg })
hl(0, "NvimTreeFolderName", { fg = colors.primary })
hl(0, "NvimTreeFolderIcon", { fg = colors.primary })
hl(0, "NvimTreeOpenedFolderName", { fg = colors.primary_container, bold = true })
hl(0, "NvimTreeEmptyFolderName", { fg = colors.outline })
hl(0, "NvimTreeRootFolder", { fg = colors.secondary, bold = true })
hl(0, "NvimTreeFileName", { fg = colors.fg })
hl(0, "NvimTreeExecFile", { fg = colors.tertiary })
hl(0, "NvimTreeSpecialFile", { fg = colors.secondary, underline = true })
hl(0, "NvimTreeIndentMarker", { fg = colors.outline_variant })
hl(0, "NvimTreeGitDirty", { fg = colors.tertiary })
hl(0, "NvimTreeGitNew", { fg = colors.tertiary })
hl(0, "NvimTreeGitDeleted", { fg = colors.error })
hl(0, "NvimTreeCursorLine", { bg = colors.surface_low })

-- Bufferline
hl(0, "BufferLineFill", { bg = colors.surface })
hl(0, "BufferLineSeparator", { fg = colors.surface, bg = colors.surface })
hl(0, "BufferLineBackground", { fg = colors.outline, bg = colors.surface })
hl(0, "BufferLineBufferVisible", { fg = colors.outline, bg = colors.surface })
hl(0, "BufferLineModified", { fg = colors.tertiary, bg = colors.surface })
hl(0, "BufferLineModifiedVisible", { fg = colors.tertiary, bg = colors.surface })
hl(0, "BufferLineWarning", { fg = colors.tertiary, bg = colors.surface })
hl(0, "BufferLineWarningDiagnostic", { fg = colors.tertiary, bg = colors.surface })
hl(0, "BufferLineError", { fg = colors.error, bg = colors.surface })
hl(0, "BufferLineErrorDiagnostic", { fg = colors.error, bg = colors.surface })
hl(0, "BufferLineInfo", { fg = colors.primary, bg = colors.surface })
hl(0, "BufferLineHint", { fg = colors.secondary, bg = colors.surface })


hl(0, "BufferLineBufferSelected", { fg = colors.fg, bg = "NONE", bold = true, italic = true })
hl(0, "BufferLineIndicatorSelected", { fg = colors.primary, bg = "NONE" })
hl(0, "BufferLineModifiedSelected", { fg = colors.tertiary, bg = "NONE" })
hl(0, "BufferLineWarningSelected", { fg = colors.tertiary, bg = "NONE", bold = true })
hl(0, "BufferLineWarningDiagnosticSelected", { fg = colors.tertiary, bg = "NONE", bold = true })
hl(0, "BufferLineErrorSelected", { fg = colors.error, bg = "NONE", bold = true })
hl(0, "BufferLineErrorDiagnosticSelected", { fg = colors.error, bg = "NONE", bold = true })
hl(0, "BufferLineDevIconDefaultSelected", { fg = colors.outline, bg = "NONE" })


-- Gitsigns
hl(0, "GitSignsAdd", { fg = colors.tertiary })
hl(0, "GitSignsChange", { fg = colors.secondary })
hl(0, "GitSignsDelete", { fg = colors.error })
hl(0, "GitSignsAddLn", { fg = colors.on_tertiary_container, bg = colors.tertiary_container })
hl(0, "GitSignsChangeLn", { fg = colors.on_secondary_container, bg = colors.secondary_container })
hl(0, "GitSignsDeleteLn", { fg = colors.on_error, bg = colors.error_container })

-- WhichKey
hl(0, "WhichKey", { fg = colors.primary, bold = true })
hl(0, "WhichKeyGroup", { fg = colors.secondary })
hl(0, "WhichKeyDesc", { fg = colors.fg })
hl(0, "WhichKeySeparator", { fg = colors.outline })
hl(0, "WhichKeyFloat", { bg = colors.surface })
hl(0, "WhichKeyBorder", { fg = colors.outline, bg = colors.surface })

-- Notify
hl(0, "NotifyERRORBorder", { fg = colors.error })
hl(0, "NotifyWARNBorder", { fg = colors.tertiary })
hl(0, "NotifyINFOBorder", { fg = colors.primary })
hl(0, "NotifyDEBUGBorder", { fg = colors.outline })
hl(0, "NotifyTRACEBorder", { fg = colors.secondary })
hl(0, "NotifyERRORIcon", { fg = colors.error })
hl(0, "NotifyWARNIcon", { fg = colors.tertiary })
hl(0, "NotifyINFOIcon", { fg = colors.primary })
hl(0, "NotifyERRORTitle", { fg = colors.error })
hl(0, "NotifyWARNTitle", { fg = colors.tertiary })
hl(0, "NotifyINFOTitle", { fg = colors.primary })
hl(0, "NotifyBackground", { bg = colors.bg })

-- Trouble
hl(0, "TroubleNormal", { fg = colors.fg, bg = colors.bg })
hl(0, "TroubleText", { fg = colors.fg })
hl(0, "TroubleCount", { fg = colors.on_primary_container, bg = colors.primary_container })
hl(0, "TroubleIndent", { fg = colors.outline_variant })

-- Dashboard
hl(0, "DashboardHeader", { fg = colors.primary })
hl(0, "DashboardCenter", { fg = colors.fg })
hl(0, "DashboardShortCut", { fg = colors.secondary })
hl(0, "DashboardFooter", { fg = colors.outline, italic = true })

-- Cmp
hl(0, "CmpItemAbbr", { fg = colors.fg })
hl(0, "CmpItemAbbrDeprecated", { fg = colors.outline, strikethrough = true })
hl(0, "CmpItemAbbrMatch", { fg = colors.primary, bold = true })
hl(0, "CmpItemAbbrMatchFuzzy", { fg = colors.primary, bold = true })
hl(0, "CmpItemKind", { fg = colors.secondary })
hl(0, "CmpItemMenu", { fg = colors.outline })
hl(0, "CmpItemKindFunction", { fg = colors.primary })
hl(0, "CmpItemKindMethod", { fg = colors.primary })
hl(0, "CmpItemKindVariable", { fg = colors.fg })
hl(0, "CmpItemKindKeyword", { fg = colors.secondary })
hl(0, "CmpItemKindText", { fg = colors.fg })
hl(0, "CmpItemKindClass", { fg = colors.primary_container })
hl(0, "CmpItemKindInterface", { fg = colors.primary_container })
hl(0, "CmpItemKindModule", { fg = colors.primary })
hl(0, "CmpItemKindProperty", { fg = colors.primary })
hl(0, "CmpItemKindSnippet", { fg = colors.tertiary })

-- Flash
hl(0, "FlashLabel", { fg = colors.on_tertiary, bg = colors.tertiary, bold = true })
hl(0, "FlashMatch", { fg = colors.on_primary_container, bg = colors.primary_container })
hl(0, "FlashCurrent", { fg = colors.on_secondary_container, bg = colors.secondary_container })
hl(0, "FlashBackdrop", { fg = colors.outline })

-- Winbar / Navic
hl(0, "WinBar", { fg = colors.fg, bg = colors.bg })
hl(0, "WinBarNC", { fg = colors.outline, bg = colors.bg })
hl(0, "NavicText", { fg = colors.fg })
hl(0, "NavicSeparator", { fg = colors.outline })
hl(0, "NavicIconsFunction", { fg = colors.primary })
hl(0, "NavicIconsMethod", { fg = colors.primary })
hl(0, "NavicIconsClass", { fg = colors.primary_container })
hl(0, "NavicIconsModule", { fg = colors.primary })
hl(0, "NavicIconsVariable", { fg = colors.fg })
