# -----------------------------------------------------
# ▄▀█ █▄░█ █ █▀▄▀█ ▄▀█ ▀█▀ █ █▀█ █▄░█
# █▀█ █░▀█ █ █░▀░█ █▀█ ░█░ █ █▄█ █░▀█
#
# name "BlackNode-Linear"
# -----------------------------------------------------

animations {
    enabled = 1

    bezier = linear, 1, 1, 1, 1
    bezier = decel, 0.05, 0.7, 0.1, 1

    animation = windows, 1, 2, decel, slide
    animation = windowsIn, 1, 2, decel, slide
    animation = windowsOut, 1, 2, decel, slide
    animation = windowsMove, 1, 2, decel, slide

    animation = fadeIn, 1, 3, linear
    animation = fadeOut, 1, 3, linear

    animation = workspaces, 1, 3, decel, slidevert
    animation = workspacesIn, 1, 3, decel, slidevert
    animation = workspacesOut, 1, 3, decel, slidevert

    animation = border, 1, 1, linear
    animation = borderangle, 1, 30, linear, loop
}
