#  ██▓███   ██▀███   ▒█████    ▄████  ██▀███   ▄▄▄       ███▄ ▄███▓
# ▓██░  ██▒▓██ ▒ ██▒▒██▒  ██▒ ██▒ ▀█▒▓██ ▒ ██▒▒████▄    ▓██▒▀█▀ ██▒
# ▓██░ ██▓▒▓██ ░▄█ ▒▒██░  ██▒▒██░▄▄▄░▓██ ░▄█ ▒▒██  ▀█▄  ▓██    ▓██░
# ▒██▄█▓▒ ▒▒██▀▀█▄  ▒██   ██░░▓█  ██▓▒██▀▀█▄  ░██▄▄▄▄██ ▒██    ▒██
# ▒██▒ ░  ░░██▓ ▒██▒░ ████▓▒░░▒▓███▀▒░██▓ ▒██▒ ▓█   ▓██▒▒██▒   ░██▒
# ▒▓▒░ ░  ░░ ▒▓ ░▒▓░░ ▒░▒░▒░  ░▒   ▒ ░ ▒▓ ░▒▓░ ▒▒   ▓▒█░░ ▒░   ░  ░
# ░▒ ░       ░▒ ░ ▒░  ░ ▒ ▒░   ░   ░   ░▒ ░ ▒░  ▒   ▒▒ ░░  ░      ░
# ░░         ░░   ░ ░ ░ ░ ▒  ░ ░   ░   ░░   ░   ░   ▒   ░      ░
#             ░         ░ ░        ░    ░           ░  ░       ░
#

$terminal = kitty

# Scripts programs

$clipboard = ~/.config/rofi/clipboard/launcher.sh
$shotcut = ~/.config/rofi/shotcut/script.sh
$wallselect = ~/.config/rofi/wallselect/script.sh
$wifi = ~/.config/rofi/wifi/script.sh
$launcher = rofi -show drun
$battery = ~/.local/bin/battery.sh
$volume = ~/.local/bin/volume.sh
$wf-recorder = ~/.config/rofi/wf-recorder/script.sh
$bn-menu = ~/.local/bin/bn-menu
$screenshot = ~/.config/rofi/hyprshot/script.sh
$music-p = ~/.config/rofi/musicPlayer/script.sh
$animation = ~/.config/rofi/animation/script.sh
$waybar_theme = ~/.config/waybar/Scripts/launcher/script.sh
$launch = ~/.config/waybar/Scripts/launcher/script.sh
$logout = ~/.config/rofi/powermenu/script.sh
$theme_launcher = ~/.config/rofi/launcher/script.sh

# Apps

$browser = firefox
$audio = pavucontrol
$lock = hyprlock
$fileManager = dolphin
$music = spotify # Change this if necessary
$logout-w = wlogout -b 6

# extra
