local colors = require("core.highlights.colors")

local hl = vim.api.nvim_set_hl

hl(0, "Normal", { fg = colors.fg, bg = colors.bg })
hl(0, "NormalNC", { fg = colors.fg, bg = colors.bg })
hl(0, "NormalFloat", { fg = colors.fg, bg = colors.surface })
hl(0, "FloatBorder", { fg = colors.outline, bg = colors.surface })
hl(0, "FloatTitle", { fg = colors.primary, bg = colors.surface, bold = true })

hl(0, "Cursor", { fg = colors.bg, bg = colors.fg })
hl(0, "CursorLine", { bg = colors.surface_low })
hl(0, "CursorLineNr", { fg = colors.primary, bold = true })
hl(0, "CursorColumn", { bg = colors.surface_low })
hl(0, "ColorColumn", { bg = colors.surface_low })

hl(0, "LineNr", { fg = colors.outline })
hl(0, "SignColumn", { bg = colors.bg })
hl(0, "EndOfBuffer", { fg = colors.bg })
hl(0, "Whitespace", { fg = colors.outline_variant })
hl(0, "NonText", { fg = colors.outline_variant })
hl(0, "SpecialKey", { fg = colors.outline_variant })
hl(0, "Conceal", { fg = colors.outline })

hl(0, "Visual", { fg = colors.on_primary_container, bg = colors.primary_container })
hl(0, "VisualNOS", { fg = colors.on_primary_container, bg = colors.primary_container })

hl(0, "Search", { fg = colors.on_tertiary_container, bg = colors.tertiary_container })
hl(0, "IncSearch", { fg = colors.on_tertiary, bg = colors.tertiary })
hl(0, "CurSearch", { fg = colors.on_tertiary, bg = colors.tertiary })

hl(0, "Pmenu", { fg = colors.fg, bg = colors.surface })
hl(0, "PmenuSel", { fg = colors.on_primary_container, bg = colors.primary_container })
hl(0, "PmenuSbar", { bg = colors.surface_low })
hl(0, "PmenuThumb", { bg = colors.outline })
hl(0, "PmenuKind", { fg = colors.secondary, bg = colors.surface })
hl(0, "PmenuKindSel", { fg = colors.on_primary_container, bg = colors.primary_container })
hl(0, "PmenuExtra", { fg = colors.outline, bg = colors.surface })
hl(0, "PmenuExtraSel", { fg = colors.on_primary_container, bg = colors.primary_container })

hl(0, "StatusLine", { fg = colors.fg, bg = colors.surface })
hl(0, "StatusLineNC", { fg = colors.outline, bg = colors.bg })
hl(0, "WinSeparator", { fg = colors.outline_variant })
hl(0, "VertSplit", { fg = colors.outline_variant })

hl(0, "Title", { fg = colors.primary, bold = true })
hl(0, "Directory", { fg = colors.primary })
hl(0, "MoreMsg", { fg = colors.primary })
hl(0, "Question", { fg = colors.primary })
hl(0, "ModeMsg", { fg = colors.fg, bold = true })
hl(0, "MsgArea", { fg = colors.fg })
hl(0, "MsgSeparator", { fg = colors.outline })
hl(0, "WarningMsg", { fg = colors.tertiary })
hl(0, "ErrorMsg", { fg = colors.error })

hl(0, "MatchParen", { fg = colors.tertiary, bold = true, underline = true })
hl(0, "WildMenu", { fg = colors.on_primary_container, bg = colors.primary_container })

hl(0, "DiffAdd", { fg = colors.on_tertiary_container, bg = colors.tertiary_container })
hl(0, "DiffChange", { fg = colors.on_secondary_container, bg = colors.secondary_container })
hl(0, "DiffDelete", { fg = colors.on_error, bg = colors.error_container })
hl(0, "DiffText", { fg = colors.on_primary_container, bg = colors.primary_container, bold = true })

hl(0, "Folded", { fg = colors.outline, bg = colors.surface_low })
hl(0, "FoldColumn", { fg = colors.outline })

hl(0, "SpellBad", { sp = colors.error, undercurl = true })
hl(0, "SpellCap", { sp = colors.secondary, undercurl = true })
hl(0, "SpellLocal", { sp = colors.tertiary, undercurl = true })
hl(0, "SpellRare", { sp = colors.primary, undercurl = true })

hl(0, "Comment", { fg = colors.outline, italic = true })
hl(0, "Constant", { fg = colors.secondary })
hl(0, "String", { fg = colors.tertiary })
hl(0, "Character", { fg = colors.tertiary })
hl(0, "Number", { fg = colors.secondary })
hl(0, "Boolean", { fg = colors.secondary })
hl(0, "Float", { fg = colors.secondary })
hl(0, "Identifier", { fg = colors.fg })
hl(0, "Function", { fg = colors.primary })
hl(0, "Statement", { fg = colors.secondary })
hl(0, "Conditional", { fg = colors.secondary })
hl(0, "Repeat", { fg = colors.secondary })
hl(0, "Label", { fg = colors.secondary })
hl(0, "Operator", { fg = colors.on_surface_variant })
hl(0, "Keyword", { fg = colors.secondary })
hl(0, "Exception", { fg = colors.secondary })
hl(0, "PreProc", { fg = colors.primary })
hl(0, "Include", { fg = colors.primary })
hl(0, "Define", { fg = colors.primary })
hl(0, "Macro", { fg = colors.primary })
hl(0, "PreCondit", { fg = colors.primary })
hl(0, "Type", { fg = colors.primary_container })
hl(0, "StorageClass", { fg = colors.secondary })
hl(0, "Structure", { fg = colors.primary_container })
hl(0, "Typedef", { fg = colors.primary_container })
hl(0, "Special", { fg = colors.tertiary })
hl(0, "SpecialChar", { fg = colors.tertiary })
hl(0, "Tag", { fg = colors.primary })
hl(0, "Delimiter", { fg = colors.on_surface_variant })
hl(0, "SpecialComment", { fg = colors.outline, italic = true })
hl(0, "Debug", { fg = colors.error })
hl(0, "Underlined", { underline = true })
hl(0, "Ignore", { fg = colors.outline })
hl(0, "Error", { fg = colors.on_error, bg = colors.error_container })
hl(0, "Todo", { fg = colors.on_tertiary_container, bg = colors.tertiary_container, bold = true })
