-- Generated by matugen for Hyprland v0.55 (Lua config)
-- Project: BlackNode
-- File: themes/colors.lua

local colors = {
    background = "0xbd111318",
    foreground = "0xffe1e2e9",

    color0 = "0xff111318",
    color1 = "0xffa6c8ff",
    color2 = "0xffbdc7dc",
    color3 = "0xffdabde2",
    color4 = "0xff234776",
    color5 = "0xff3d4758",
    color6 = "0xff553f5d",
    color7 = "0xffe1e2e9",

    color8 = "0xff43474e",
    color9 = "0xffa6c8ff",
    color10 = "0xffbdc7dc",
    color11 = "0xffdabde2",
    color12 = "0xff234776",
    color13 = "0xff3d4758",
    color14 = "0xff553f5d",
    color15 = "0xff2e3035",
}

return colors
