# BACKGROUND
background {
    monitor =
    path = ~/.config/hypr/hyprlock.png
    blur_passes = 3
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# GENERAL
general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = false
}

# PROFILE PHOTO
image {
    monitor =
    path = ~/.config/hypr/vivek.png

    border_size = 2
    border_color = rgba(255,255,255,0)

    size = 92

    rounding = -1
    rotate = 0

    reload_time = -1

    position = 0, 28
    halign = center
    valign = center
}

# DATE
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%A, %B %d")"

    color = rgba(216,222,233,0.70)

    font_size = 17
    font_family = SF Pro Display Bold

    position = 0, 248
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%I:%M")</span>"

    color = rgba(216,222,233,0.70)

    font_size = 85
    font_family = SF Pro Display Bold

    position = 0, 177
    halign = center
    valign = center
}

# USER BOX
shape {
    monitor =

    size = 213, 42

    color = rgba(255,255,255,0.10)

    rounding = -1
    border_size = 0
    border_color = rgba(253,198,135,0)

    rotate = 0
    xray = false

    position = 0, -92
    halign = center
    valign = center
}

# USER
label {
    monitor =

    text = $USER

    color = rgba(216,222,233,0.80)

    outline_thickness = 2

    font_size = 12
    font_family = SF Pro Display Bold

    position = 0, -92
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =

    size = 213, 42

    outline_thickness = 2

    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true

    outer_color = rgba(0,0,0,0)
    inner_color = rgba(255,255,255,0.10)

    font_color = rgb(200,200,200)

    fade_on_empty = false

    font_family = SF Pro Display Bold

    placeholder_text = <i><span foreground="##ffffff99">Enter Pass</span></i>

    hide_input = false

    position = 0, -149
    halign = center
    valign = center
}

# CURRENT SONG
label {
    monitor =

    text = cmd[update:1000] echo "$(~/.config/hypr/Scripts/songdetail.sh)"

    color = rgba(255,255,255,0.60)

    font_size = 12
    font_family = JetBrains Mono Nerd Font, SF Pro Display Bold

    position = 0, 35
    halign = center
    valign = bottom
}
