background {
    monitor =
    path = ~/.config/hypr/hyprlock.png
    blur_passes = 3
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = false
}

label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%I:%M")</span>"
    color = rgba(223, 228, 221, 0.9)
    font_size = 76
    font_family = SF Pro Display Bold
    position = 0, 180
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%A, %B %d")"
    color = rgba(192, 201, 192, 0.8)
    font_size = 14
    font_family = SF Pro Display Bold
    position = 0, 120
    halign = center
    valign = center
}

image {
    monitor =
    path = ~/.config/hypr/vivek.png
    border_size = 2
    border_color = rgba(148, 213, 168, 0.8)
    size = 80
    rounding = -1
    rotate = 0
    reload_time = -1
    position = 0, 50
    halign = center
    valign = center
}

shape {
    monitor =
    size = 220, 40
    color = rgba(49, 54, 49, 0.4)
    rounding = 20
    border_size = 0
    border_color = rgba(0,0,0,0)
    rotate = 0
    xray = false
    position = 0, -10
    halign = center
    valign = center
}

label {
    monitor =
    text = $USER
    color = rgba(223, 228, 221, 0.7)
    outline_thickness = 2
    font_size = 14
    font_family = SF Pro Display Bold
    position = 0, -10
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 260, 44
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(148, 213, 168, 0.5)
    inner_color = rgba(38, 43, 39, 0.5)
    font_color = rgba(223, 228, 221, 0.9)
    fade_on_empty = false
    font_family = SF Pro Display Bold
    placeholder_text = <span foreground="rgba(192, 201, 192, 0.5)">Enter Password</span>
    hide_input = false
    position = 0, -65
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(~/.config/hypr/Scripts/songdetail.sh)"
    color = rgba(192, 201, 192, 0.6)
    font_size = 12
    font_family = JetBrains Mono Nerd Font, SF Pro Display Bold
    position = 0, 30
    halign = center
    valign = bottom
}
