general {
    lock_cmd = pidof hyprlock || hyprlock

    before_sleep_cmd = loginctl lock-session && ~/.local/bin/blacknode-continuity.sh --save
    after_sleep_cmd = hyprctl dispatch dpms on && ~/.local/bin/blacknode-greeter.sh

    inhibit_sleep = 3

    ignore_dbus_inhibit = false
    ignore_systemd_inhibit = false
    ignore_wayland_inhibit = false
}

listener {
    timeout = 120
    on-timeout = brightnessctl -s set 20%
    on-resume = brightnessctl -r
}

listener {
    timeout = 120
    on-timeout = brightnessctl -sd rgb:kbd_backlight set 0
    on-resume = brightnessctl -rd rgb:kbd_backlight
}

listener {
    timeout = 180
    on-timeout = playerctl --all-players pause
}

listener {
    timeout = 300
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on && brightnessctl -r
}

listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
