# .s    s.
#       SS. .s5 s.  .s5SSSs.  .s5SSSs.  .s        .s5SSSs.  .s    s.  .s5SSSs.
# sS    S%S     SS.       SS.       SS.                 SS.       SS.       SS.
# SS    S%S ssS SSS sS    S%S sS    S%S sS        sS    S%S sSs.  S%S sS    S%S
# SSSs. S%S  SSSSS  SS .sS::' SS .sS;:' SS        SSSs. S%S SS `S.S%S SS    S%S
# SS    S%S   SSS   SS        SS    ;,  SS        SS    S%S SS  `sS%S SS    S%S
# SS    `:;   `:;   SS        SS    `:; SS        SS    `:; SS    `:; SS    `:;
# SS    ;,.   ;,.   SS        SS    ;,. SS    ;,. SS    ;,. SS    ;,. SS    ;,.
# :;    ;:'   ;:'   `:        `:    ;:' `:;;;;;:' :;    ;:' :;    ;:' ;;;;;;;:'
#

source = ~/.config/hypr/settings/general.conf
source = ~/.config/hypr/settings/env.conf
source = ~/.config/hypr/settings/rules.conf
source = ~/.config/hypr/settings/programs.conf
source = ~/.config/hypr/settings/autostart.conf
source = ~/.config/hypr/keybinds/keybinds.conf
source = ~/.config/hypr/keybinds/input.conf
source = ~/.config/hypr/themes/decoration.conf
source = ~/.config/hypr/animations.conf
