# wallust v3.4
#
# You can copy this file to ~/.config/wallust/wallust.toml (keep in mind is a sample config)

# SIMPLE TUTORIAL, or `man wallust.5`:
# https://explosion-mental.codeberg.page/wallust/
#
# If comming from v2: https://explosion-mental.codeberg.page/wallust/v3.html#wallusttoml

# Global section - values below can be overwritten by command line flags

# How the image is parse, in order to get the colors:
# full - resized - wal - thumb -  fastresize - kmeans
backend = "full"

# What color space to use to produce and select the most prominent colors:
# lab - labmixed - lch - lchmixed
color_space = "lchmixed"

# Use the most prominent colors in a way that makes sense, a scheme color palette:
# dark - dark16 - darkcomp - darkcomp16
# light - light16 - lightcomp - lightcomp16
# harddark - harddark16 - harddarkcomp - harddarkcomp16
# softdark - softdark16 - softdarkcomp - softdarkcomp16
# softlight - softlight16 - softlightcomp - softlightcomp16
palette = "harddark16"

# Ensures a "readable contrast" (OPTIONAL, disabled by default)
# Should only be enabled when you notice an unreadable contrast frequently happening
# with your images. The reference color for the contrast is the background color.
#check_contrast = true

# Color saturation, between [1% and 100%] (OPTIONAL, disabled by default)
# usually something higher than 50 increases the saturation and below
# decreases it (on a scheme with strong and vivid colors)
saturation = 50

# Alpha value for templating, by default 100 (no other use whatsoever)
#alpha = 100

[templates]
waybar = { template = 'waybar.css', target = '~/.cache/wallust/waybar.css' }
rofi = { template = 'rofi.rasi', target = '~/.cache/wallust/rofi.rasi' }
kitty = { template = 'kitty.conf', target = '~/.config/kitty/colors-wallust.conf' }
hyprland = { template = 'hyprland.conf', target = '~/.cache/wallust/hyprland.conf' }
cava = { template = 'cava', target = '~/.config/cava/config' }
dunst = { template = 'dunst', target = '~/.config/dunst/dunstrc' }
nvim = { template = 'wallust.lua', target = '~/.config/nvim/lua/core/wallust_colors.lua' }
clipse = { template = 'clipse.json', target = '~/.config/clipse/colors.json' }
p10k = { template = 'p10k.zsh', target = '~/.p10k.zsh' }
