#   ██████ ▄▄▄█████▓ ▄▄▄       ██▀███  ▄▄▄█████▓
# ▒██    ▒ ▓  ██▒ ▓▒▒████▄    ▓██ ▒ ██▒▓  ██▒ ▓▒
# ░ ▓██▄   ▒ ▓██░ ▒░▒██  ▀█▄  ▓██ ░▄█ ▒▒ ▓██░ ▒░
#   ▒   ██▒░ ▓██▓ ░ ░██▄▄▄▄██ ▒██▀▀█▄  ░ ▓██▓ ░
# ▒██████▒▒  ▒██▒ ░  ▓█   ▓██▒░██▓ ▒██▒  ▒██▒ ░
# ▒ ▒▓▒ ▒ ░  ▒ ░░    ▒▒   ▓▒█░░ ▒▓ ░▒▓░  ▒ ░░
# ░ ░▒  ░ ░    ░      ▒   ▒▒ ░  ░▒ ░ ▒░    ░
# ░  ░  ░    ░        ░   ▒     ░░   ░   ░
#       ░                 ░  ░   ░
#


exec-once = hyprctl setcursor Bibata-Modern-Classic 24
exec-once = awww-daemon # old manager for wallpaper, "hyprpaper", now is "awww"
exec-once = hypridle
exec-once = nm-applet
exec-once = waybar && dunst
exec-once = clipse -listen
exec = ~/.local/bin/battery_chargin.sh
exec = ~/.local/bin/battery_low.sh
exec = ~/.local/bin/battery_high.sh && ~/.local/bin/wifi_alert.sh
