#   ▄████ ▓█████  ███▄    █ ▓█████  ██▀███  ▓█████ ▄▄▄       ██▓
#  ██▒ ▀█▒▓█   ▀  ██ ▀█   █ ▓█   ▀ ▓██ ▒ ██▒▓█   ▀▒████▄    ▓██▒
# ▒██░▄▄▄░▒███   ▓██  ▀█ ██▒▒███   ▓██ ░▄█ ▒▒███  ▒██  ▀█▄  ▒██░
# ░▓█  ██▓▒▓█  ▄ ▓██▒  ▐▌██▒▒▓█  ▄ ▒██▀▀█▄  ▒▓█  ▄░██▄▄▄▄██ ▒██░
# ░▒▓███▀▒░▒████▒▒██░   ▓██░░▒████▒░██▓ ▒██▒░▒████▒▓█   ▓██▒░██████▒
#  ░▒   ▒ ░░ ▒░ ░░ ▒░   ▒ ▒ ░░ ▒░ ░░ ▒▓ ░▒▓░░░ ▒░ ░▒▒   ▓▒█░░ ▒░▓  ░
#   ░   ░  ░ ░  ░░ ░░   ░ ▒░ ░ ░  ░  ░▒ ░ ▒░ ░ ░  ░ ▒   ▒▒ ░░ ░ ▒  ░
# ░ ░   ░    ░      ░   ░ ░    ░     ░░   ░    ░    ░   ▒     ░ ░
#       ░    ░  ░         ░    ░  ░   ░        ░  ░     ░  ░    ░  ░
#

source = ~/.cache/wallust/hyprland.conf

general {
    gaps_in = 3
    gaps_out = 7
    border_size = 2
    # col.active_border = $color5 $background $color5 145deg
    col.active_border = rgb($color5) rgb($background) rgb($color5) 145deg
    col.inactive_border = rgb(24273A) rgb(24273A) rgb(24273A)
    resize_on_border = false
    allow_tearing = false
    layout = dwindle
}
