$primary = rgb(c0ce7e)
$on_primary = rgb(2c3400)
$primary_container = rgb(414c08)
$on_primary_container = rgb(dcea97)

$secondary = rgb(c5c9a8)
$on_secondary = rgb(2e321b)
$secondary_container = rgb(45492f)
$on_secondary_container = rgb(e1e5c2)

$tertiary = rgb(a2d0c3)
$on_tertiary = rgb(05372f)
$tertiary_container = rgb(214e45)
$on_tertiary_container = rgb(bdecdf)

$error = rgb(ffb4ab)
$on_error = rgb(690005)

$background = rgb(13140d)
$on_background = rgb(e4e3d6)

$surface = rgb(13140d)
$on_surface = rgb(e4e3d6)
$surface_variant = rgb(46483b)
$on_surface_variant = rgb(c7c7b7)

$outline = rgb(919283)
$outline_variant = rgb(46483b)

$shadow = rgb(000000)
$scrim = rgb(000000)

$inverse_surface = rgb(e4e3d6)
$inverse_on_surface = rgb(303129)
$inverse_primary = rgb(586420)
