$primary = rgb(ffb695)
$on_primary = rgb(542105)
$primary_container = rgb(713619)
$on_primary_container = rgb(ffdbcc)

$secondary = rgb(e6bead)
$on_secondary = rgb(442a1f)
$secondary_container = rgb(5d4034)
$on_secondary_container = rgb(ffdbcc)

$tertiary = rgb(d1c88f)
$on_tertiary = rgb(363106)
$tertiary_container = rgb(4e471b)
$on_tertiary_container = rgb(eee4a9)

$error = rgb(ffb4ab)
$on_error = rgb(690005)

$background = rgb(1a120e)
$on_background = rgb(f1dfd8)

$surface = rgb(1a120e)
$on_surface = rgb(f1dfd8)
$surface_variant = rgb(52443d)
$on_surface_variant = rgb(d8c2ba)

$outline = rgb(a08d85)
$outline_variant = rgb(52443d)

$shadow = rgb(000000)
$scrim = rgb(000000)

$inverse_surface = rgb(f1dfd8)
$inverse_on_surface = rgb(382e2a)
$inverse_primary = rgb(8e4d2e)
