# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#ece1d4"

# Title color for boxes
theme[title]="#f1be6d"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#dbc3a1"

# Background color of selected item in processes box
theme[selected_bg]="#f1be6d"

# Foreground color of selected item in processes box
theme[selected_fg]="#432c00"

# Color of inactive/disabled text
theme[inactive_fg]="#d2c4b4"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#b5cea4"

# Cpu box outline color
theme[cpu_box]="#9b8f80"

# Memory/disks box outline color
theme[mem_box]="#9b8f80"

# Net up/down box outline color
theme[net_box]="#9b8f80"

# Processes box outline color
theme[proc_box]="#9b8f80"

# Box divider line and small boxes line color
theme[div_line]="#4e4539"

# Temperature graph colors
theme[temp_start]="#dbc3a1"
theme[temp_mid]="#f1be6d"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#dbc3a1"
theme[cpu_mid]="#f1be6d"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#dbc3a1"
theme[free_mid]=""
theme[free_end]="#55442a"

# Mem/Disk cached meter
theme[cached_start]="#b5cea4"
theme[cached_mid]=""
theme[cached_end]="#384c2c"

# Mem/Disk available meter
theme[available_start]="#f1be6d"
theme[available_mid]=""
theme[available_end]="#604100"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

# Download graph colors
theme[download_start]="#dbc3a1"
theme[download_mid]="#f1be6d"
theme[download_end]="#b5cea4"

# Upload graph colors
theme[upload_start]="#dbc3a1"
theme[upload_mid]="#f1be6d"
theme[upload_end]="#b5cea4"
