-- Generated by matugen for Hyprland v0.55 (Lua config)
-- Project: BlackNode
-- File: themes/colors.lua

background = "0f1511"
foreground = "dfe4dd"

color0 = "0f1511"
color1 = "94d5a8"
color2 = "b6ccb9"
color3 = "a3cddb"
color4 = "0e512f"
color5 = "374b3d"
color6 = "214c57"
color7 = "dfe4dd"

color8 = "414942"
color9 = "94d5a8"
color10 = "b6ccb9"
color11 = "a3cddb"
color12 = "0e512f"
color13 = "374b3d"
color14 = "214c57"
color15 = "2c322d"
