-- Generated by matugen for Hyprland v0.55 (Lua config)
-- Project: BlackNode
-- File: themes/colors.lua

background = "1a120e"
foreground = "f1dfd8"

color0 = "1a120e"
color1 = "ffb695"
color2 = "e6bead"
color3 = "d1c88f"
color4 = "713619"
color5 = "5d4034"
color6 = "4e471b"
color7 = "f1dfd8"

color8 = "52443d"
color9 = "ffb695"
color10 = "e6bead"
color11 = "d1c88f"
color12 = "713619"
color13 = "5d4034"
color14 = "4e471b"
color15 = "382e2a"
