-- Generated by matugen for Hyprland v0.55 (Lua config)
-- Project: BlackNode
-- File: themes/colors.lua

background = "101417"
foreground = "dfe3e8"

color0 = "101417"
color1 = "94cdf7"
color2 = "b7c9d9"
color3 = "cec0e8"
color4 = "004c6e"
color5 = "384956"
color6 = "4c4163"
color7 = "dfe3e8"

color8 = "41474d"
color9 = "94cdf7"
color10 = "b7c9d9"
color11 = "cec0e8"
color12 = "004c6e"
color13 = "384956"
color14 = "4c4163"
color15 = "2d3135"
