$main_bg = rgb()
$main_fg = rgb()
$accent = rgb()
$accent_alt = rgb()
$surface = rgb()
$selected_bg = rgb()

$col_active_border = rgb() rgb() 45deg
$col_inactive_border = rgb()
$col_bg = rgb()
$col_text = rgb()
