$primary = rgb(bdce80)
$on_primary = rgb(293500)
$primary_container = rgb(3e4c0b)
$on_primary_container = rgb(d9eb9a)

$secondary = rgb(c4caa9)
$on_secondary = rgb(2d331b)
$secondary_container = rgb(444930)
$on_secondary_container = rgb(e0e6c3)

$tertiary = rgb(a1d0c5)
$on_tertiary = rgb(033730)
$tertiary_container = rgb(214e46)
$on_tertiary_container = rgb(bdece1)

$error = rgb(ffb4ab)
$on_error = rgb(690005)

$background = rgb(13140d)
$on_background = rgb(e4e3d7)

$surface = rgb(13140d)
$on_surface = rgb(e4e3d7)
$surface_variant = rgb(46483c)
$on_surface_variant = rgb(c7c8b8)

$outline = rgb(909283)
$outline_variant = rgb(46483c)

$shadow = rgb(000000)
$scrim = rgb(000000)

$inverse_surface = rgb(e4e3d7)
$inverse_on_surface = rgb(303129)
$inverse_primary = rgb(566423)
