$primary = rgb(ddb9f8)
$on_primary = rgb(3f2358)
$primary_container = rgb(573a70)
$on_primary_container = rgb(f1daff)

$secondary = rgb(d1c1d9)
$on_secondary = rgb(372c3f)
$secondary_container = rgb(4e4256)
$on_secondary_container = rgb(eeddf6)

$tertiary = rgb(f3b7bc)
$on_tertiary = rgb(4c2529)
$tertiary_container = rgb(663a3f)
$on_tertiary_container = rgb(ffdadc)

$error = rgb(ffb4ab)
$on_error = rgb(690005)

$background = rgb(151217)
$on_background = rgb(e8e0e8)

$surface = rgb(151217)
$on_surface = rgb(e8e0e8)
$surface_variant = rgb(4b454d)
$on_surface_variant = rgb(cdc4ce)

$outline = rgb(968e98)
$outline_variant = rgb(4b454d)

$shadow = rgb(000000)
$scrim = rgb(000000)

$inverse_surface = rgb(e8e0e8)
$inverse_on_surface = rgb(332f35)
$inverse_primary = rgb(705289)
