$primary = rgb(87d6bd)
$on_primary = rgb(00382c)
$primary_container = rgb(005140)
$on_primary_container = rgb(a3f2d8)

$secondary = rgb(b2ccc2)
$on_secondary = rgb(1d352d)
$secondary_container = rgb(344c43)
$on_secondary_container = rgb(cee9dd)

$tertiary = rgb(a8cbe2)
$on_tertiary = rgb(0e3446)
$tertiary_container = rgb(284b5e)
$on_tertiary_container = rgb(c4e7ff)

$error = rgb(ffb4ab)
$on_error = rgb(690005)

$background = rgb(0f1512)
$on_background = rgb(dee4e0)

$surface = rgb(0f1512)
$on_surface = rgb(dee4e0)
$surface_variant = rgb(3f4945)
$on_surface_variant = rgb(bfc9c3)

$outline = rgb(89938e)
$outline_variant = rgb(3f4945)

$shadow = rgb(000000)
$scrim = rgb(000000)

$inverse_surface = rgb(dee4e0)
$inverse_on_surface = rgb(2b322f)
$inverse_primary = rgb(116b56)
