# -----------------------------------------------------
# ▄▀█ █▄░█ █ █▀▄▀█ ▄▀█ ▀█▀ █ █▀█ █▄░█
# █▀█ █░▀█ █ █░▀░█ █▀█ ░█░ █ █▄█ █░▀█
#
# name "BlackNode-Eclipse"
# -----------------------------------------------------

animations {
    enabled = 1

    bezier = shot, 0.2, 1, 0.3, 1
    bezier = swipe, 0.6, 0, 0.4, 1
    bezier = bounce, 0.1, 1.1, 0.3, 1.1
    bezier = easeInOutExpo, 0.87, 0, 0.13, 1

    animation = windows, 1, 5, bounce, popin 80%
    animation = windowsIn, 1, 5, bounce, popin 80%
    animation = windowsOut, 1, 5, swipe, popin 80%
    animation = windowsMove, 1, 5, shot, slide

    animation = fadeIn, 1, 4, easeInOutExpo
    animation = fadeOut, 1, 4, easeInOutExpo
    animation = fadeSwitch, 1, 4, easeInOutExpo

    animation = workspaces, 1, 5, shot, slide
    animation = workspacesIn, 1, 5, shot, slide
    animation = workspacesOut, 1, 5, shot, slide

    animation = layers, 1, 4, bounce, slide
    animation = layersIn, 1, 4, bounce, slide
    animation = layersOut, 1, 4, swipe, slide
}
