# -----------------------------------------------------
# ▄▀█ █▄░█ █ █▀▄▀█ ▄▀█ ▀█▀ █ █▀█ █▄░█
# █▀█ █░▀█ █ █░▀░█ █▀█ ░█░ █ █▄█ █░▀█
#
# name "BlackNode-Motion"
# -----------------------------------------------------

animations {
    enabled = 1

    bezier = fluent_decel, 0, 0.2, 0.4, 1
    bezier = easeOutExpo, 0.16, 1, 0.3, 1
    bezier = soft_bounce, 0.05, 0.9, 0.1, 1.05
    bezier = md3_standard, 0.2, 0, 0, 1
    bezier = quick_in, 0.1, 0.9, 0.2, 1

    animation = windows, 1, 3, soft_bounce, slide
    animation = windowsIn, 1, 3, soft_bounce, slide
    animation = windowsOut, 1, 3, fluent_decel, slide
    animation = windowsMove, 1, 3, soft_bounce, slide

    animation = fadeIn, 1, 3, md3_standard
    animation = fadeOut, 1, 3, md3_standard
    animation = fadeSwitch, 1, 3, md3_standard
    animation = fadeShadow, 1, 3, md3_standard
    animation = fadeDim, 1, 3, md3_standard
    animation = fadeLayers, 1, 3, md3_standard

    animation = workspaces, 1, 4, quick_in, slidevert
    animation = workspacesIn, 1, 4, quick_in, slidevert
    animation = workspacesOut, 1, 4, quick_in, slidevert

    animation = layers, 1, 3, easeOutExpo, slide
    animation = layersIn, 1, 3, easeOutExpo, slide
    animation = layersOut, 1, 3, easeOutExpo, slide

    animation = border, 1, 10, default
    animation = borderangle, 1, 30, default, loop
}
