# -----------------------------------------------------
# ▄▀█ █▄░█ █ █▀▄▀█ ▄▀█ ▀█▀ █ █▀█ █▄░█
# █▀█ █░▀█ █ █░▀░█ █▀█ ░█░ █ █▄█ █░▀█
#
# name "BlackNode-Flow"
# -----------------------------------------------------

animations {
    enabled = 1

    bezier = fluid, 0.76, 0, 0.24, 1
    bezier = snappy, 0.33, 1, 0.68, 1
    bezier = overshot, 0.13, 0.99, 0.29, 1.1

    animation = windows, 1, 4, overshot, slide
    animation = windowsIn, 1, 4, overshot, slide left
    animation = windowsOut, 1, 4, fluid, slide right
    animation = windowsMove, 1, 4, overshot, slide

    animation = fadeIn, 1, 5, fluid
    animation = fadeOut, 1, 5, fluid

    animation = workspaces, 1, 6, fluid, slide
    animation = workspacesIn, 1, 6, fluid, slide
    animation = workspacesOut, 1, 6, fluid, slide

    animation = layers, 1, 5, snappy, slide
    animation = layersIn, 1, 5, snappy, slide
    animation = layersOut, 1, 5, fluid, slide
}
