# -----------------------------------------------------
# ▄▀█ █▄░█ █ █▀▄▀█ ▄▀█ ▀█▀ █ █▀█ █▄░█
# █▀█ █░▀█ █ █░▀░█ █▀█ ░█░ █ █▄█ █░▀█
#
# name "BlackNode-Elastic"
# -----------------------------------------------------

animations {
    enabled = 1

    bezier = elastic, 0.6, -0.28, 0.735, 0.045
    bezier = bounceOut, 0.175, 0.885, 0.32, 1.275
    bezier = smooth, 0.45, 0, 0.55, 1

    animation = windows, 1, 6, bounceOut, slide
    animation = windowsIn, 1, 6, bounceOut, slide top
    animation = windowsOut, 1, 5, elastic, slide bottom
    animation = windowsMove, 1, 6, bounceOut, slide

    animation = fadeIn, 1, 4, smooth
    animation = fadeOut, 1, 4, smooth

    animation = workspaces, 1, 5, bounceOut, slide
    animation = workspacesIn, 1, 5, bounceOut, slide
    animation = workspacesOut, 1, 5, smooth, slide

    animation = layers, 1, 4, bounceOut, slide
    animation = layersIn, 1, 4, bounceOut, slide
    animation = layersOut, 1, 4, elastic, slide
}
